import { Header } from '@/widgets/Header'
import '@/core/styles/index.scss'
import { Footer } from '@/widgets/Footer';
import { roboto } from '@/core/fonts/fonts';
import { StoreProvider } from '@/core/providers/StoreProvider';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutProps{
  children: React.ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
    return (
        <html lang="en" className={roboto.className}>
            <body>
                <StoreProvider>
                    <div className="app">
                        <Header />
                        <div className='page'>{children}</div>
                        <Footer />
                        <div className='selectContainer'/>
                    </div>
                </StoreProvider>
            </body>
        </html>
    )
}
